baseURL = 'https://icaps24.icaps-conference.org'
languageCode = 'en-us'
title = 'ICAPS 2024'
theme = 'mainroad'

[Params.logo]
  image = "img/icapslogo.png" # Logo image. Path relative to "static"
  title = "The 34th International Conference" # Logo title, otherwise will use site title
  title2 = "on Automated Planning and Scheduling"
  subtitle = "Banff, Alberta, Canada, June 1-6, 2024" # Logo subtitle

[Params.style.vars]
     highlightColor = "#f5821f"

[menu]
# HOME
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url="/home"
    weight = 1000
# DATES
  [[menu.main]]
    identifier = "dates"
    name = "Dates"
    url="/dates"
    weight = 2000
# COMPETITIONS
  [[menu.main]]
    identifier = "competitions"
    name = "Competitions"
    url="/competitions"
    weight = 3000
  [[menu.main]]
    identifier = "airlift"
    name = "Airlift Challenge"
    url="/competitions/airlift"
    parent = "competitions"
    weight = 10
# STUDENTS
  [[menu.main]]
    identifier = "students"
    name = "Students"
    weight = 4000
  [[menu.main]]
    identifier = "summerschool"
    name = "Summer School"
    url = "/summerschool"
    parent = "students"
    weight = 100
  [[menu.main]]
    identifier = "dc"
    name = "Doctoral Consortium"
    url = "/calls/dc"
    parent = "students"
    weight = 200
# ATTENDING
#  [[menu.main]]
#    identifier = "attending"
#    name = "Attending"
#    weight = 3000
#  [[menu.main]]
#    identifier = "venue"
#    name = "Venue"
#    url = "/attending/venue"
#    parent = "attending"
#    weight = 10
#  [[menu.main]]
#    identifier = "travel"
#    name = "Travel Information"
#    url = "/attending/travel"
#    parent = "attending"
#    weight = 20
#  [[menu.main]]
#    identifier = "registration"
#    name = "Registration"
#    url = "/attending/registration"
#    parent = "attending"
#    weight = "30"
#  [[menu.main]]
#    identifier = "accommodation"
#    name = "Accommodation"
#    url = "/attending/accommodation"
#    parent = "attending"
#    weight = "40"
#  [[menu.main]]
#    identifier = "student-support"
#    name = "Student Support"
#    url = "/attending/students"
#    parent = "attending"
#    weight = "50"
## CALLS
  [[menu.main]]
    identifier = "calls"
    name = "Calls"
    weight = 4000
  [[menu.main]]
    identifier = "main_track"
    name = "Call for Papers"
    url = "/calls/main_track"
    parent = "calls"
    weight = 10
#  [[menu.main]]
#    identifier = "application_track"
#    name = "Application Track"
#    url = "/calls/application_track"
#    parent = "calls"
#    weight = 20
#  [[menu.main]]
#    identifier = "learning_track"
#    name = "Learning Track"
#    url = "/calls/learning_track"
#    parent = "calls"
#    weight = 30
#  [[menu.main]]
#    identifier = "robotics_track"
#    name = "Robotics Track"
#    url = "/calls/robotics_track"
#    parent = "calls"
#    weight = 40
#  [[menu.main]]
#    identifier = "journal_track"
#    name = "Journal Track"
#    url = "/calls/journal_track"
#    parent = "calls"
#    weight = 45
  [[menu.main]]
    identifier = "workshop_call"
    name = "Call for Workshop Proposals"
    url = "/calls/workshop_call"
    parent = "calls"
    weight = 50
  [[menu.main]]
    identifier = "tutorial_call"
    name = "Call for Tutorial Proposals"
    url = "/calls/tutorial_call"
    parent = "calls"
    weight = 50
#  [[menu.main]]
#    identifier = "demo_track"
#    name = "System Demonstrations"
#    url = "/calls/demo_track"
#    parent = "calls"
#    weight = 70
 [[menu.main]]
   identifier = "dc_call"
   name = "Call for Doctoral Consortium"
   url = "/calls/dc"
   parent = "calls"
   weight = 80
 [[menu.main]]
   identifier = "ss_call"
   name = "Call for Summer School"
   url = "/summerschool"
   parent = "calls"
   weight = 90
#  [[menu.main]]
#    identifier = "partnership_call"
#    name = "Call for Partnership"
#    url = "/calls/partnership_call"
#    parent = "calls"
#    weight = 90
## COMPETITIONS
#  [[menu.main]]
#    identifier = "competitions"
#    name = "Competitions"
#    url="/competitions"
#    weight = 5000
# SUBMISSIONS
#  [[menu.main]]
#    identifier = "submissions"
#    name = "Submissions"
#    url="/submissions"
#    weight = 6000
# PROGRAM
 [[menu.main]]
   identifier = "program"
   name = "Program"
   weight = 7000
#  [[menu.main]]
#    identifier = "overview"
#    name = "Program Overview"
#    url = "/program/overview"
#    parent = "program"
#    weight = 10
#  [[menu.main]]
#    identifier = "accepted-papers"
#    name = "Accepted Papers"
#    url = "/program/accepted"
#    parent = "program"
#    weight = "15"
#  [[menu.main]]
#    identifier = "doctoral-consortium"
#    name = "Doctoral Consortium"
#    url = "/program/dc"
#    parent = "program"
#    weight = 20
#  [[menu.main]]
#    identifier = "keynotes"
#    name = "Keynotes"
#    url = "/program/keynotes"
#    parent = "program"
#    weight = "30"
 [[menu.main]]
   identifier = "ws"
   name = "Workshops"
   parent = "program"
   url = "/program/ws_overview"
   weight = 40
#  [[menu.main]]
#    identifier = "tutorials"
#    parent = "program"
#    name = "Tutorials"
#    url = "/program/tutorial_overview"
#    weight = "50"
# TUTORIALS
#  [[menu.main]]
#    identifier = "mdp_modeling"
#    name = "Introduction to MDP Modeling and Interaction via RDDL and pyRDDLGym"
#    parent = "tutorials"
#    url = "/program/tutorials/mdp_modeling"
#    weight = "10"
#  [[menu.main]]
#    identifier = "hard"
#    name = "How hard can it be? The computational complexity of planning"
#    parent = "tutorials"
#    url = "/program/tutorials/hard"
#    weight = "20"
#  [[menu.main]]
#    identifier = "tnetworks"
#    name = "Recent Advances in Temporal Networks for Planning and Scheduling"
#    parent = "tutorials"
#    url = "/program/tutorials/tnetworks"
#    weight = "30"
#  [[menu.main]]
#    identifier = "model"
#    name = "Model Acquisition in the Modern Era"
#    parent = "tutorials"
#    url = "/program/tutorials/model"
#    weight = "40"
#  [[menu.main]]
#    identifier = "up"
#    name = "Unified Planning: A Python Library Making Planning Technology Accessible"
#    parent = "tutorials"
#    url = "/program/tutorials/up"
#    weight = "50"
## WORKSHOPS
 [[menu.main]]
   identifier = "keps"
   name = "KEPS"
   parent = "ws"
   url = "/program/workshops/keps"
   weight = 10
  [[menu.main]]
    identifier = "hplan"
    name = "HPlan"
    url = "/program/workshops/hplan"
    parent = "ws"
    weight = 20
 [[menu.main]]
   identifier = "wipc"
   name = "WIPC"
   url = "/program/workshops/wipc"
   parent = "ws"
   weight = 30
  [[menu.main]]
    identifier = "prl"
    name = "PRL"
    parent = "ws"
    url = "/program/workshops/prl"
    weight = 40
  [[menu.main]]
    identifier = "haxp"
    name = "HAXP"
    url = "/program/workshops/haxp"
    parent = "ws"
    weight = 50
  [[menu.main]]
    identifier = "haxp"
    name = "HAXP"
    parent = "ws"
    url = "/program/workshops/haxp"
    weight = 60
  [[menu.main]]
    identifier = "weep"
    name = "WEEP"
    parent = "ws"
    url = "/program/workshops/weep"
    weight = 70
 [[menu.main]]
   identifier = "rddps"
   name = "RDDPS"
   parent = "ws"
   url = "/program/workshops/rddps"
   weight = 80
  [[menu.main]]
    identifier = "hsdip"
    name = "HSDIP"
    parent = "ws"
    url = "/program/workshops/hsdip"
    weight = 90
 [[menu.main]]
   identifier = "planrob"
   name = "PlanRob"
   parent = "ws"
   url = "/program/workshops/planrob"
   weight = 100

# COMMITTEES
  [[menu.main]]
    identifier = "committees"
    name = "Committees"
    weight = 9000
  [[menu.main]]
    identifier = "organizers"
    name = "Organizers"
    url = "/committees/organizers"
    parent = "committees"
    weight = 100
  [[menu.main]]
    identifier = "pc"
    name = "Program Committee"
    url = "/committees/program_committees"
    parent = "committees"
    weight = 200
# CODE OF CONDUCT
  [[menu.main]]
    identifier = "code_of_conduct"
    name = "Code of Conduct"
    url = "/code_of_conduct"
    weight = 10000


[markup.goldmark.renderer]
  unsafe = true



